[server]
enableCORS = false
enableXsrfProtection = false
 
[client]
showErrorDetails = true
 
[runner]
# Allow HTML rendering in st.markdown() calls
magicEnabled = true
 
[theme]
primaryColor = "#4ea2ff"
backgroundColor = "#0b0f19"
secondaryBackgroundColor = "#131b2e"
textColor = "#f1f5f9"
font = "sans serif"